export const GET_VOUCHERS = "GET_VOUCHERS";
export const CREATE_VOUCHER_REQUEST = "CREATE_VOUCHER_REQUEST";
export const CREATE_VOUCHER_SUCCESS = "CREATE_VOUCHER_SUCCESS";
export const CREATE_VOUCHER_FAILURE = "CREATE_VOUCHER_FAILURE";

export const UPDATE_VOUCHER_REQUEST = "UPDATE_VOUCHER_REQUEST";
export const UPDATE_VOUCHER_SUCCESS = "UPDATE_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_FAILURE = "UPDATE_VOUCHER_FAILURE";

export const DELETE_VOUCHER_REQUEST = "DELETE_VOUCHER_REQUEST";
export const DELETE_VOUCHER_SUCCESS = "DELETE_VOUCHER_SUCCESS";
export const DELETE_VOUCHER_FAILURE = "DELETE_VOUCHER_FAILURE";

export const GET_VOUCHER_BY_ID_REQUEST = "GET_VOUCHER_BY_ID_REQUEST";
export const GET_VOUCHER_BY_ID_SUCCESS = "GET_VOUCHER_BY_ID_SUCCESS";
export const GET_VOUCHER_BY_ID_FAILURE = "GET_VOUCHER_BY_ID_FAILURE";
