export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const CREATE_INGREDIENT_REQUEST = "CREATE_INGREDIENT_REQUEST";
export const CREATE_INGREDIENT_SUCCESS = "CREATE_INGREDIENT_SUCCESS";
export const CREATE_INGREDIENT_FAILURE = "CREATE_INGREDIENT_FAILURE";

export const UPDATE_INGREDIENT_REQUEST = "UPDATE_INGREDIENT_REQUEST";
export const UPDATE_INGREDIENT_SUCCESS = "UPDATE_INGREDIENT_SUCCESS";
export const UPDATE_INGREDIENT_FAILURE = "UPDATE_INGREDIENT_FAILURE";

export const DELETE_INGREDIENT_REQUEST = "DELETE_INGREDIENT_REQUEST";
export const DELETE_INGREDIENT_SUCCESS = "DELETE_INGREDIENT_SUCCESS";
export const DELETE_INGREDIENT_FAILURE = "DELETE_INGREDIENT_FAILURE";

export const GET_INGREDIENT_BY_ID_REQUEST = "GET_INGREDIENT_BY_ID_REQUEST";
export const GET_INGREDIENT_BY_ID_SUCCESS = "GET_INGREDIENT_BY_ID_SUCCESS";
export const GET_INGREDIENT_BY_ID_FAILURE = "GET_INGREDIENT_BY_ID_FAILURE";

export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS";
export const GET_EXPENSE_FAILURE = "GET_EXPENSE_FAILURE";
