
export const GET_PRODUCTS_SUCCESS= 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE= 'GET_PRODUCTS_FAILURE';
export const CREATE_PRODUCT_SUCCESS= 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE= 'CREATE_PRODUCT_FAILURE';
export const UPDATE_PRODUCT_SUCCESS= 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE= 'UPDATE_PRODUCT_FAILURE';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS= 'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE= 'GET_PRODUCTS_BY_CATEGORY_FAILURE';
