export const GET_BILLS_SUCCESS = 'GET_BILLS_SUCCESS';
export const GET_BILLS_FAILURE = 'GET_BILLS_FAILURE';

export const CREATE_BILL_SUCCESS = 'CREATE_BILL_SUCCESS';
export const CREATE_BILL_FAILURE = 'CREATE_BILL_FAILURE';

export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS';
export const UPDATE_BILL_FAILURE = 'UPDATE_BILL_FAILURE';

export const GET_BILLS_BY_ACCOUNT_SUCCESS = 'GET_BILLS_BY_ACCOUNT_SUCCESS';
export const GET_BILLS_BY_ACCOUNT_FAILURE = 'GET_BILLS_BY_ACCOUNT_FAILURE';

export const GET_BILL_BY_ID_SUCCESS = 'GET_BILL_BY_ID_SUCCESS';
export const GET_BILL_BY_ID_FAILURE = 'GET_BILL_BY_ID_FAILURE';
