export const GET_OPTIONALS = "GET_OPTIONALS";
export const CREATE_OPTIONAL_REQUEST = "CREATE_OPTIONAL_REQUEST";
export const CREATE_OPTIONAL_SUCCESS = "CREATE_OPTIONAL_SUCCESS";
export const CREATE_OPTIONAL_FAILURE = "CREATE_OPTIONAL_FAILURE";

export const UPDATE_OPTIONAL_REQUEST = "UPDATE_OPTIONAL_REQUEST";
export const UPDATE_OPTIONAL_SUCCESS = "UPDATE_OPTIONAL_SUCCESS";
export const UPDATE_OPTIONAL_FAILURE = "UPDATE_OPTIONAL_FAILURE";

export const DELETE_OPTIONAL_REQUEST = "DELETE_OPTIONAL_REQUEST";
export const DELETE_OPTIONAL_SUCCESS = "DELETE_OPTIONAL_SUCCESS";
export const DELETE_OPTIONAL_FAILURE = "DELETE_OPTIONAL_FAILURE";

export const GET_OPTIONAL_BY_ID_REQUEST = "GET_OPTIONAL_BY_ID_REQUEST";
export const GET_OPTIONAL_BY_ID_SUCCESS = "GET_OPTIONAL_BY_ID_SUCCESS";
export const GET_OPTIONAL_BY_ID_FAILURE = "GET_OPTIONAL_BY_ID_FAILURE";
