export const GET_CHOICES_BY_OPTIONAL_ID = "GET_CHOICES_BY_OPTIONAL_ID";
export const CREATE_CHOICE_REQUEST = "CREATE_CHOICE_REQUEST";
export const CREATE_CHOICE_SUCCESS = "CREATE_CHOICE_SUCCESS";
export const CREATE_CHOICE_FAILURE = "CREATE_CHOICE_FAILURE";

export const UPDATE_CHOICE_REQUEST = "UPDATE_CHOICE_REQUEST";
export const UPDATE_CHOICE_SUCCESS = "UPDATE_CHOICE_SUCCESS";
export const UPDATE_CHOICE_FAILURE = "UPDATE_CHOICE_FAILURE";

export const DELETE_CHOICE_REQUEST = "DELETE_CHOICE_REQUEST";
export const DELETE_CHOICE_SUCCESS = "DELETE_CHOICE_SUCCESS";
export const DELETE_CHOICE_FAILURE = "DELETE_CHOICE_FAILURE";

export const GET_CHOICE_BY_ID_REQUEST = "GET_CHOICE_BY_ID_REQUEST";
export const GET_CHOICE_BY_ID_SUCCESS = "GET_CHOICE_BY_ID_SUCCESS";
export const GET_CHOICE_BY_ID_FAILURE = "GET_CHOICE_BY_ID_FAILURE";
